name: specificask
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  provider: ^6.1.5
  shared_preferences: ^2.3.3
  loading_animation_widget: ^1.3.0
  iconsax: ^0.0.8
  http: ^1.4.0
  intl: ^0.20.2
  shimmer: ^3.0.0
  syncfusion_flutter_datagrid: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          style: normal
